### PR TITLE
Added the iolyser-App.

### PR DESCRIPTION
**Pull request by olagino**
There is a small bug from ftrobopy but in general this app works perfectly.

### CODE REVIEW

**Comment by ski7777** [comment]
I will test it today.

Raphael

**Review by harbaum — COMMENTED** [review]
Looks like the io test app we really need. Will give  it a test run asap ...

**Comment by olagino** [comment]
I've planned a few other features, to take photos of the camera and a more advanced motor control interface. But I will realize this later, the general functionality is in my opinion more important.

**Comment by harbaum** [comment]
I am actually a friend of small apps with a sharply focussed use case. Saving photos to sd card would imho be better done in a seperate photo app which can later be equipped with all kinds of photo related extras.

**Comment by rkunze** [comment]
I'm of the same opinion as @harbaum here - small apps which focus on one task are better than one huge app that tries to do everything.

In this case, my recommendation is to extend the existing camera_test app from the core repository into a real camera app instead of grafting photo functions onto an io test app.

I think this is a better fit for the hardware as well. The iolyzer is usable (and useful) on every TXT, while a camera app (or a camera function in iolyzer) obviously needs a camera to work.

**Comment by harbaum** [comment]
Works for me and looks useful -> Merged!

Thanks a lot!

**Pull request merged**
